---
name: Deno build

on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: ./build.ts
        working-directory: ./bids-validator
      - uses: actions/upload-artifact@v4
        with:
          name: main
          path: bids-validator/dist/validator

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
      fail-fast: false
    defaults:
      run:
        working-directory: ./bids-validator

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno test --allow-all --coverage=cov/ src/
      - name: Collect coverage
        run: deno coverage cov/ --lcov --output=coverage.lcov
        if: ${{ always() }}
      - uses: codecov/codecov-action@v4
        if: ${{ always() }}
        with:
          files: coverage.lcov

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && github.repository_owner == 'bids-standard'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Set credentials
        run: |
          git config --global user.name "BIDS-Bot"
          git config --global user.email "bids-maintenance@users.noreply.github.com"
      - name: Save describe stamp
        run: echo VERSION=$( git describe ) >> $GITHUB_ENV
      - name: Checkout orphan
        run: |
          git checkout deno-build
          git rm -rf .
      - uses: actions/download-artifact@v4
        with:
          name: main
          path: main
      - name: Create shim, adjust version, and commit to new branch
        run: |
          mv main/main.js .
          mv main/bids-validator.js .
          sed -i -e "s,version(\"alpha\"),version(\"${VERSION}.deno\"),g" bids-validator.js
          echo -e '#!/usr/bin/env bash\n\ndeno run --allow-read --allow-write --allow-env --allow-net --allow-run "$(dirname "$0")"/bids-validator.js "$@"' >| bids-validator
          chmod a+x bids-validator
          git add main.js bids-validator.js bids-validator
          git commit -m "BLD: $VERSION [skip ci]" || true
      - name: Push
        run: git push origin deno-build
