name: Node Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node: [14]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Set git name/email
        run: |
          git config --global user.email "bids.maintenance@gmail.com"
          git config --global user.name "bids-maintenance"
      - name: Set up Python ${{ matrix.python-version }}
        run: npm install -g npm@^7
        run: npm install
      - name: Eslint
        run: npm run lint
      - name: Get bids-examples data
        run: git submodule update --init
      - name: Jest tests
        run: npm run coverage -- --maxWorkers=2 --testTimeout=10000
      - name: Upload to codecov
        run: npm run codecov
      - name: Smoke tests
        run: |
          bids-validator/bin/bids-validator bids-validator/tests/data/valid_headers/ --ignoreNiftiHeaders
          bids-validator/bin/bids-validator bids-validator/tests/data/valid_headers/ --ignoreNiftiHeaders --json


